services:
  app:
    container_name: metamcp
    build: .
    # image: ghcr.io/metatool-ai/metamcp:latest
    # pull_policy: always
    env_file:
      - .env
    ports:
      - "12008:12008"
    volumes:
      - /mnt/nas/services/postgres/certs/postgres.crt:/app/postgres.crt:ro
      # Mount Docker socket for Docker-in-Docker support
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Postgres connection details
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-metamcp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-m3t4mcp}
      POSTGRES_DB: ${POSTGRES_DB:-metamcp_db}
      
      # Database configuration (composed from above vars)
      DATABASE_URL: postgresql://${POSTGRES_USER:-metamcp_user}:${POSTGRES_PASSWORD:-m3t4mcp}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-metamcp_db}?sslmode=verify-full&sslrootcert=/app/postgres.crt
      
      # Application URL configuration
      APP_URL: ${APP_URL:-http://localhost:12008}
      NEXT_PUBLIC_APP_URL: ${APP_URL:-http://localhost:12008}
      
      # Auth configuration
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-your-super-secret-key-change-this-in-production}
      
      # Docker networking fix
      TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ${TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL:-true}
      
      # Docker-in-Docker configuration
      DOCKER_HOST: unix:///var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    networks:
      - metamcp-network

networks:
  metamcp-network:
    driver: bridge
